name: 🐛 Bug Report
description: Something is wrong with universe.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!

        Security issue?
        ======================
        Any security issues should be submitted directly to [vs101ff@gmail.com](mailto:vs101ff@gmail.com)
  - type: input
    attributes:
      label: What version of universe are you using?
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Node are you using? Minimum supported version is 16.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: OS
      description: What operating system are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any Other info.
    validations:
      required: false
